Repository scoutmaker/scoutmaker-backend-v2-nest, pull requests merged in 2022-12, with the labels that each got.

#142 [SCOUT-283] add date constraint to players team include
  src/modules/players/players.service.ts
  src/modules/reports/reports.service.ts
Labels: REVIEW DONE

#147 [SCOUT-291] players filters
  src/app.module.ts
  src/modules/organization-player-acl/dto/create-organization-player-ace.dto.ts
  src/modules/organization-player-acl/dto/find-all-organization-player-ace.dto.ts
  src/modules/organization-player-acl/dto/organization-player-ace-pagination-options.dto.ts
  src/modules/organization-player-acl/dto/organization-player-ace.dto.ts
  src/modules/organization-player-acl/dto/update-organization-player-ace.dto.ts
  src/modules/organization-player-acl/organization-player-acl.controller.spec.ts
  src/modules/organization-player-acl/organization-player-acl.controller.ts
  src/modules/organization-player-acl/organization-player-acl.module.ts
  src/modules/organization-player-acl/organization-player-acl.service.spec.ts
  src/modules/organization-player-acl/organization-player-acl.service.ts
  src/modules/players/guards/delete.guard.ts
  src/modules/players/guards/read.guard.ts
  src/modules/players/guards/update.guard.ts
  src/modules/players/interceptors/access-filters.interceptor.ts
  src/modules/players/players.module.ts
  src/modules/user-player-acl/dto/create-user-player-ace.dto.ts
  src/modules/user-player-acl/dto/find-all-user-player-ace.dto.ts
  src/modules/user-player-acl/dto/update-user-player-ace.dto.ts
  src/modules/user-player-acl/dto/user-player-ace-pagination-options.dto.ts
  src/modules/user-player-acl/dto/user-player-ace.dto.ts
  src/modules/user-player-acl/user-player-acl.controller.spec.ts
  src/modules/user-player-acl/user-player-acl.controller.ts
  src/modules/user-player-acl/user-player-acl.module.ts
  src/modules/user-player-acl/user-player-acl.service.spec.ts
  src/modules/user-player-acl/user-player-acl.service.ts
Labels: REVIEW DONE

#148 [SCOUT-286] update delete guards
  src/common/guards/admin-or-author.guard.ts
  src/i18n/en/common.json
  src/i18n/pl/common.json
  src/modules/agencies/agencies.controller.ts
  src/modules/agencies/agencies.module.ts
  src/modules/clubs/clubs.controller.ts
  src/modules/clubs/clubs.module.ts
  src/modules/competition-groups/competition-groups.controller.ts
  src/modules/competition-participations/competition-participations.controller.ts
  src/modules/countries/countries.controller.ts
  src/modules/insider-notes/guards/delete.guard.ts
  src/modules/insider-notes/guards/update.guard.ts
  src/modules/insider-notes/insider-notes.controller.ts
  src/modules/insider-notes/insider-notes.module.ts
  src/modules/matches/guards/delete.guard.ts
  src/modules/matches/guards/update.guard.ts
  src/modules/matches/matches.controller.ts
  src/modules/matches/matches.module.ts
  src/modules/notes/guards/delete.guard.ts
  src/modules/notes/guards/update.guard.ts
  src/modules/notes/notes.controller.ts
  src/modules/notes/notes.module.ts
  src/modules/player-positions/player-positions.controller.ts
  src/modules/players/guards/delete.guard.ts
  src/modules/players/guards/update.guard.ts
  src/modules/players/players.controller.ts
  src/modules/players/players.module.ts
  src/modules/regions/regions.controller.ts
  src/modules/report-templates/report-templates.controller.ts
  src/modules/report-templates/report-templates.module.ts
  src/modules/reports/guards/delete.guard.ts
  src/modules/reports/guards/update.guard.ts
  src/modules/reports/reports.controller.ts
  src/modules/reports/reports.module.ts
  src/modules/seasons/seasons.controller.ts
  src/modules/team-affiliations/team-affiliations.controller.ts
  src/modules/team-affiliations/team-affiliations.module.ts
  src/modules/teams/teams.controller.ts
  src/modules/teams/teams.module.ts
  src/modules/user-football-roles/user-football-roles.controller.ts
Labels: REVIEW DONE

#137 Feat/scout 259 dashboard
  src/app.module.ts
  src/modules/dashboard/dashboard.controller.spec.ts
  src/modules/dashboard/dashboard.controller.ts
  src/modules/dashboard/dashboard.module.ts
  src/modules/dashboard/dashboard.service.spec.ts
  src/modules/dashboard/dashboard.service.ts
  src/modules/dashboard/dto/dashboard.dto.ts
  src/modules/dashboard/transform-subscriptions.ts
  src/modules/matches/matches.service.ts
  src/modules/notes/dto/notes-pagination-options.dto.ts
  src/modules/notes/notes.service.ts
  src/modules/organizations/organizations.service.ts
  src/modules/players/players.service.ts
  src/modules/reports/dto/reports-pagination-options.dto.ts
  src/modules/reports/reports.service.ts
  src/modules/users/dto/user.dto.ts
  src/modules/users/users.service.ts
  src/utils/helpers.ts
Labels: REVIEW DONE, v1.1

#154 add sorting option
  src/modules/matches/dto/matches-pagination-options.dto.ts
  src/modules/notes/dto/notes-pagination-options.dto.ts
  src/modules/notes/notes.service.ts
  src/modules/players/dto/players-pagination-options.dto.ts
Labels: REVIEW DONE, v1.2

#155 add match sorting
  src/modules/reports/dto/reports-pagination-options.dto.ts
  src/modules/reports/reports.service.ts
Labels: REVIEW DONE, v1.2

#157 add teams count
  src/modules/clubs/clubs.service.ts
  src/modules/clubs/dto/club.dto.ts
Labels: REVIEW DONE, v1.2

#156 add missing match include
  src/modules/reports/reports.service.ts
Labels: REVIEW DONE, v1.2

#158 implement percentageRatingRanges
  src/modules/notes/dto/find-all-notes.dto.ts
  src/modules/notes/notes.service.ts
  src/modules/reports/dto/find-all-reports.dto.ts
  src/modules/reports/reports.service.ts
  src/types/common.ts
  src/utils/constants.ts
Labels: REVIEW DONE, v1.2
